version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-ui:
          context: AWS
          filters:
            branches:
              only: main
      - deploy-ui:
          context: AWS
          requires:
            - build-and-push-ui
          filters:
            branches:
              only: main

jobs:
  build-and-push-ui:
    machine:
      image: ubuntu-2004:202107-02
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t snapdeploy-ui .
            docker tag snapdeploy-ui:latest $ECR_REGISTRY/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker tag snapdeploy-ui:latest $ECR_REGISTRY/snapdeploy-dev-ui:latest
            docker push $ECR_REGISTRY/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker push $ECR_REGISTRY/snapdeploy-dev-ui:latest

  deploy-ui:
    docker:
      - image: cimg/python:3.9
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update ECS Service
          command: |
            aws ecs update-service \
              --cluster snapdeploy-dev-cluster \
              --service snapdeploy-dev-ui \
              --force-new-deployment
