version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@8.2.0
  aws-ecs: circleci/aws-ecs@2.2.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-ui:
          context: aws-credentials
          filters:
            branches:
              only: main
      - deploy-ui:
          context: aws-credentials
          requires:
            - build-and-push-ui
          filters:
            branches:
              only: main

jobs:
  build-and-push-ui:
    executor: aws-ecr/default
    steps:
      - checkout
      - aws-ecr/build-and-push-image:
          repo: snapdeploy-dev-ui
          tag: ${CIRCLE_SHA1:0:7},latest
          region: eu-west-1
          dockerfile: Dockerfile
          path: .

  deploy-ui:
    executor: aws-ecs/default
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - aws-ecs/update-service:
          family: snapdeploy-dev-ui
          cluster-name: snapdeploy-dev-cluster
          service-name: snapdeploy-dev-ui
          container-image-name-updates: "container=ui,tag=${CIRCLE_SHA1:0:7}"
