version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-ui:
          context:
            - AWS
            - API
            - Clerk
          filters:
            branches:
              only: main
      - deploy-ui:
          context: AWS
          requires:
            - build-and-push-ui
          filters:
            branches:
              only: main

jobs:
  build-and-push-ui:
    docker:
      - image: cimg/node:20.11
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - setup_remote_docker
      - aws-cli/setup
      - run:
          name: Verify Environment Variables
          command: |
            echo "Checking environment variables..."
            echo "VITE_API_URL is set: ${VITE_API_URL:+YES}"
            echo "VITE_API_URL value: ${VITE_API_URL}"
            echo "VITE_CLERK_PUBLISHABLE_KEY is set: ${VITE_CLERK_PUBLISHABLE_KEY:+YES}"
            echo "VITE_CLERK_PUBLISHABLE_KEY prefix: ${VITE_CLERK_PUBLISHABLE_KEY:0:20}..."
            echo "ECR_REGISTRY: ${ECR_REGISTRY}"
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REGISTRY
      - run:
          name: Build and Push Docker Image
          command: |
            echo "=== Full Environment Variable Values ==="
            echo "VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY"
            echo "VITE_API_URL=$VITE_API_URL"
            echo "========================================="
            docker build \
              --progress=plain \
              --no-cache \
              --build-arg VITE_CLERK_PUBLISHABLE_KEY=$VITE_CLERK_PUBLISHABLE_KEY \
              --build-arg VITE_API_URL=$VITE_API_URL \
              -t snapdeploy-ui .
            docker tag snapdeploy-ui:latest $ECR_REGISTRY/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker tag snapdeploy-ui:latest $ECR_REGISTRY/snapdeploy-dev-ui:latest
            docker push $ECR_REGISTRY/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker push $ECR_REGISTRY/snapdeploy-dev-ui:latest

  deploy-ui:
    docker:
      - image: cimg/python:3.9
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update ECS Service
          command: |
            aws ecs update-service \
              --cluster snapdeploy-dev-cluster \
              --service snapdeploy-dev-ui \
              --force-new-deployment
