version: 2.1

orbs:
  aws-cli: circleci/aws-cli@4.0.0

workflows:
  build-and-deploy:
    jobs:
      - build-and-push-ui:
          context: aws-credentials
          filters:
            branches:
              only: main
      - deploy-ui:
          context: aws-credentials
          requires:
            - build-and-push-ui
          filters:
            branches:
              only: main

jobs:
  build-and-push-ui:
    docker:
      - image: cimg/base:stable
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Configure AWS CLI
          command: |
            aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
            aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
            aws configure set default.region $AWS_DEFAULT_REGION
      - run:
          name: Login to ECR
          command: |
            aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
      - run:
          name: Build and Push Docker Image
          command: |
            docker build -t snapdeploy-ui .
            docker tag snapdeploy-ui:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker tag snapdeploy-ui:latest $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/snapdeploy-dev-ui:latest
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/snapdeploy-dev-ui:${CIRCLE_SHA1:0:7}
            docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/snapdeploy-dev-ui:latest

  deploy-ui:
    docker:
      - image: cimg/python:3.9
    environment:
      AWS_DEFAULT_REGION: eu-west-1
    steps:
      - checkout
      - aws-cli/setup
      - run:
          name: Update ECS Service
          command: |
            aws ecs update-service \
              --cluster snapdeploy-dev-cluster \
              --service snapdeploy-dev-ui \
              --force-new-deployment
